# Copyright 2014 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

os: linux
dist: bionic
language: go

jobs:
  include:
  - go: 1.14.x
    cache:
      directories:
      - $GOPATH/pkg/mod
      # Cache tools sources.
      - $GOPATH/src/github\.com/client9
      - $GOPATH/src/github\.com/google/addlicense
      - $GOPATH/src/golang\.org
    before_script:
    - echo $TRAVIS_GO_VERSION
    - >
      go get -u -v
      github.com/client9/misspell/cmd/misspell
      github.com/google/addlicense
      golang.org/x/lint/golint
    script:
    - >
      echo 'Erroring on misspelling';
      ! misspell $(find . -type f | grep -v 'vendor/') | grep a
    - >
      echo 'Erroring on golint:';
      go list ./... | grep -v /vendor/ | xargs -L1 golint -set_exit_status
    - >
      echo 'Running tests (within GOPATH):';
      go test ./...
    - >
      echo 'Erroring if a license header is missing:';
      ! addlicense -check . | grep -v '^vendor/' | grep -v stack/state_string.go | grep -v internal/htmlstack/data.go | read
